### ISSUE TITLE
IMAP protocol line is included in the message .data

### ISSUE THREAD

**Issue by jkramer** [retupmoca/P6-Net-IMAP#15]
When using the .data method on a message, a line like `* 1 FETCH (BODY[] {47391}` is prepended to the data. In Net::IMAP::Message.data this line is parsed to get the blob size, however afterwards it's still added to the actual data. I guess it just needs a "next" after line [48](https://github.com/retupmoca/P6-Net-IMAP/blob/master/lib/Net/IMAP/Message.pm6#L48).

This bug potentially also causes the message to truncated, as the protocol line is added and therefore counts into number of read bytes, so reading might stop early, leaving some bytes in the buffer to be read sometime later (not tested, just assuming).

**Comment by jkramer** [comment]
After playing a bit more with the module I found that when using the .mime method it seems to work fine. Now I don't know if this is actually a bug and Email::MIME silently discards the line when parsing the data or if everything's how it's supposed to be...

**Comment by retupmoca** [comment]
I've added a `next` after line 48 as you suggested. I suspect that Email::MIME was effectively skipping that FETCH line.

Let me know if this still breaks on your side.
